### ISSUE TITLE
babel-loader requires webpack > 1

### ISSUE THREAD

**Issue by Si1kIfY** [proustibat/cordova-hello-world#1]
New clone / install off master

Looks like webpack needs to be added as a devDependency in the `package.json`

**Error:** 

```
└── UNMET PEER DEPENDENCY webpack@1 || 2 || ^2.1.0-beta || ^2.2.0-rc

npm WARN babel-loader@6.4.1 requires a peer of webpack@1 || 2 || ^2.1.0-beta || ^2.2.0-rc but none was installed.
```
**Env:**
```
MacOS 10.12.4
Node v7.6.0
```

**Fix:**

```
npm install webpack@1.15.0 --save-dev && rm -rf node-modules && npm install
```

Cheers 👍

**Comment by Si1kIfY** [comment]
Also webpack version requirement is `1.15.0`

**Comment by proustibat** [comment]
Thanks @Si1kIfY
This project is old, I didn't work on it since a while. I think the issue is solved with theses commits.
It works with a clone and an installation from scratch. Runs on an android device.

![screenshot_20170515-161133](https://cloud.githubusercontent.com/assets/1054387/26061856/6a1e28b2-3989-11e7-8ab7-8c1d43bdc208.png)
